# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  buf:
    desc: "generate pb files from buf.gen.yaml and buf.yaml"
    cmds:
      - buf dep update
      - buf generate

  make:user:
    cmds:
      - task buf
      - blocz add:event -d user -a lib/api/example_api.dart --update {{.CLI_ARGS}} # example: task make:user -- --repository

  make:user:proto:
    cmds:
      - task buf
      - blocz add:event -d user_proto -a proto/user.proto --update {{.CLI_ARGS}} # example: task make:user:proto -- --repository

  brun:
    aliases: ["b"]
    cmds:
      - dart run build_runner build --delete-conflicting-outputs
