name: blocz

description: Flutter bloc helpers
version: 1.4.0
repository: https://github.com/zerolethanh/blocz
homepage: https://github.com/zerolethanh/blocz

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.7.0
  analyzer: ^10.0.0
  dcli: ^8.3.0
  mustache_template: ^2.0.0
  recase: ^4.1.0
  collection: ^1.19.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  blocz:
