# https://taskfile.dev

version: "3"

vars:
  VERSION:
    sh: "grep '^version:' pubspec.yaml | awk '{print $2}'"

tasks:
  compile:
    desc: Compile binary
    aliases:
      - c
    cmds:
      - dart compile exe bin/blocz.dart -o bin/blocz
      - ls -lh bin/blocz #check file size

  compile:hasher:
    aliases:
      - ch
    cmds:
      - dcli compile -o last_build_hash_gen.dart
      - ls -lh last_build_hash_gen #check file size

  test:built:
    aliases:
      - tb
    cmds:
      - bin/blocz {{.CLI_ARGS}}

  test:
    desc: Run tests
    aliases:
      - t
    cmds:
      - dart run bin/blocz.dart {{.CLI_ARGS}}

  release:local:
    desc: Release local (compiles and copies binary to pub-cache bin)
    aliases:
      - rl
    cmds:
      - task: compile
      - task: _copy:bin:{{OS}}
      - rm bin/blocz # remove binary on done
      # - task: setup:path
      - echo " ✅ Successfully activated blocz locally."

  publish:
    desc: "Create git tag for version from pubspec.yaml and publish to pub.dev"
    cmds:
      - git tag "v{{.VERSION}}"
      - git push origin "v{{.VERSION}}"
      - dart pub publish

  _copy:bin:darwin:
    internal: true
    cmds:
      - mkdir -p "$HOME/.pub-cache/bin"
      - cp bin/blocz "$HOME/.pub-cache/bin/blocz"

  _copy:bin:linux:
    internal: true
    cmds:
      - mkdir -p "$HOME/.pub-cache/bin"
      - cp bin/blocz "$HOME/.pub-cache/bin/blocz"

  _copy:bin:windows:
    internal: true
    cmds:
      - powershell -Command "New-Item -ItemType Directory -Force -Path "$env:LOCALAPPDATA\Pub\Cache\bin""
      - powershell -Command "Copy-Item -Path 'bin\blocz.exe' -Destination "$env:LOCALAPPDATA\Pub\Cache\bin\blocz.exe" -Force"

  setup:path:
    desc: Automatically add pub cache bin to PATH based on OS
    cmds:
      - task: _setup:path:{{OS}}

  _setup:path:darwin:
    internal: true
    cmds:
      - |
        if [[ ":$PATH:" != *":$HOME/.pub-cache/bin:"* ]]; then
          echo "Adding $HOME/.pub-cache/bin to PATH in ~/.zshrc"
          echo 'export PATH="$PATH:$HOME/.pub-cache/bin"' >> ~/.zshrc
          echo "Added to ~/.zshrc. Please run 'source ~/.zshrc' or restart terminal."
        else
          echo "PATH already contains pub-cache/bin"
        fi

  _setup:path:linux:
    internal: true
    cmds:
      - |
        if [[ ":$PATH:" != *":$HOME/.pub-cache/bin:"* ]]; then
          echo "Adding $HOME/.pub-cache/bin to PATH in ~/.bashrc"
          echo 'export PATH="$PATH:$HOME/.pub-cache/bin"' >> ~/.bashrc
          echo "Added to ~/.bashrc. Please run 'source ~/.bashrc' or restart terminal."
        else
          echo "PATH already contains pub-cache/bin"
        fi

  _setup:path:windows:
    internal: true
    cmds:
      - powershell -Command "if (\$env:PATH -notlike '*Pub\Cache\bin*') { \$oldPath = [Environment]::GetEnvironmentVariable('Path', 'User'); [Environment]::SetEnvironmentVariable('Path', \$oldPath + ';\$env:LOCALAPPDATA\Pub\Cache\bin', 'User'); echo 'Added to PATH. Please restart your terminal.' } else { echo 'PATH already contains Pub\Cache\bin' }"
